# Generated by Django 5.1.5 on 2025-02-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_scannedplate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedplate',
            name='image',
            field=models.ImageField(default='A:\\Assignment\x07th sem\\project\\ALPR\x07lprServer\\media\\lp\\dummy.jpg', upload_to='lp/'),
            preserve_default=False,
        ),
    ]
